---
title: "Assignment5-Higheredu"
author: "Robert Saldivar"
date: "November 26, 2018"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#Loading packages and reading in data files

library(tidyverse)
library(ggpubr)
library(stargazer)
library(RColorBrewer)
library(extrafont)
library(car)
library(effsize)
library(knitr)
library(kableExtra)
library(onewaytests)
library(ggsignif)
library(pwr)
library(vcdExtra)
library(FSA)

Phds_1985_2015 <- read_csv("PhDs by Field 1985 - 2015-edits.csv")
Grads_1967_2015 <- read_csv("Grad enrollment 1967 - 2015-edits.csv")
Median_Salary_Postdocs <- read_csv("Median salary for doctoral recipients-edits.csv")
Faculty_Salary <- read_csv("Faculty salary data (2008 - 2009 survey)-edits.csv")
PhDs_Clean <- read_csv("PhDs_Clean.csv")
```

```{r, echo=FALSE}
#Inital data exploration grad enrollment

Grad_male_hist <- ggplot(Grads_1967_2015, aes(x=Total_Males)) +
  geom_histogram()

Grad_male_qq <- ggplot(Grads_1967_2015, aes(sample=Total_Males)) +
  geom_qq()

Grad_male_hist
Grad_male_qq

Grad_female_hist <- ggplot(Grads_1967_2015, aes(x=Total_Females)) +
  geom_histogram()

Grad_female_qq <- ggplot(Grads_1967_2015, aes(sample=Total_Females)) +
  geom_qq()

Grad_female_hist
Grad_female_qq


```


```{r, echo=FALSE}
#Trends in Graduate Enrollment
# Create a graph showing the trend of male and female grad enrollment
#Graph of total male verse female graph
total_enrollment_graph67_15 <- ggplot(Grads_1967_2015, aes(x=Year)) +
  geom_line(aes(y=Total_Females, color="Total_Females")) + 
  geom_line(aes(y=Total_Males, color="Total_Males")) +
  theme_classic() + 
  labs(x="Year", y="Student Population")+
  ggtitle("Change in Male and Female Graduate Enrollment from 1967-2015") 
  
  
total_enrollment_graph67_15

#graph of fulltime male v female enrollment
full_enroll_graph <- ggplot(Grads_1967_2015, aes(x=Year)) +
  geom_line(aes(y=Females_Full_time, color="Females_Full_time")) + 
  geom_line(aes(y=Males_Full_time, color="Males_Full_time"))

full_enroll_graph

#graph of parttime enrollment male v female
part_enroll_graph <- ggplot(Grads_1967_2015, aes(x=Year)) +
  geom_line(aes(y=Females_Part_time, color="Females_Part_time")) + 
  geom_line(aes(y=Males_Part_time, color="Males_Part_time"))

part_enroll_graph

#part and fulltime enrollment male v female
full_part_enrollgraph <- ggplot(Grads_1967_2015, aes(x=Year)) +
  geom_line(aes(y=Females_Part_time, color="Females_Part_time")) + 
  geom_line(aes(y=Males_Part_time, color="Males_Part_time")) + 
  geom_line(aes(y=Females_Full_time, color="Females_Full_time")) + 
  geom_line(aes(y=Males_Full_time, color="Males_Full_time")) 

full_part_enrollgraph

#private vs public enrollment rates
private_public_enrollgraph <- ggplot(Grads_1967_2015, aes(x=Year)) +
  geom_line(aes(y=Public), color="grey3") + 
  geom_line(aes(y=Private_Total), color="purple") +
  theme_bw()

private_public_enrollgraph

```

```{r, echo=FALSE}
#Run significance tests of on enrollment data
```


```{r, echo=FALSE}
#Wrangle PhD data
Phd_new <- Phds_1985_2015 %>%
  select('Field_of_study_and_sex','1985_Number', '2000_Number', '2015_Number') %>%
  filter(Field_of_study_and_sex !="All fields", Field_of_study_and_sex !="Otherc", Field_of_study_and_sex !="Life sciencesb", Field_of_study_and_sex !="Psychology and social sciences", Field_of_study_and_sex !="Male", Field_of_study_and_sex !="Mathematics and computer sciences", Field_of_study_and_sex !="Female")

```

```{r, echo=FALSE}
#Shifts in female PhD recipients
# Create graph or table of female Phd recipients
PhDs_Clean$Year <- factor(PhDs_Clean$Year)

Phd_graph <- ggplot(PhDs_Clean, aes(x=Year))  +
  geom_point(aes(y=Female_education, color="Female_education", size=2)) +
  geom_point(aes(y=Female_Humanities, color="Female_Humanities", size=2)) +
  geom_point(aes(y=Female_physical_sci, color="Female_physical_sci", size=2)) +
  geom_point(aes(y=Female_engineering, color="Female_engineering", size=2)) +
  theme_classic()
  
Phd_graph
# Graph still needs work
#Create table showing shift
PhDs_Clean2 <- PhDs_Clean %>%
  select(Year, Female_physical_sci, Female_engineering, Female_education, Female_Humanities)

Phd_table <- kable(PhDs_Clean2) %>%
  kable_styling(bootstrap_options = c("striped"), full_width = FALSE)

Phd_table


```

```{r, echo=FALSE}
#Run Significance test on PhD data
```


```{r, echo=FALSE}
# Explore starting salaries data

median_salary_graph <- ggplot(Median_Salary_Postdocs, aes(x=Field_of_study)) +
  geom_point(aes(y=Employment_Male, color="Employment_Male", size=0.5)) +
  geom_point(aes(y=Employment_female, color="Employment_female", size=0.5)) +
  geom_point(aes(y=Postdoctoral_study_Male, color="Postdoctoral_study_Male", size=0.5)) +
  geom_point(aes(y=Postdoctoral_study_female, color="Postdoctoral_study_female", size=0.5)) +
  scale_x_discrete()

median_salary_graph

```

```{r, echo=FALSE}
#Wrangle starting salaries data
starting_salaries_employment <- Median_Salary_Postdocs %>%
  select('Field_of_study', 'Employment_Male', 'Employment_female')

starting_salaries_postdoc <- Median_Salary_Postdocs %>%
  select('Field_of_study', 'Postdoctoral_study_Male', 'Postdoctoral_study_female')

```

```{r, echo=FALSE}
#Male and female starting salaries significance testing
#running a mann-whittney u test for employment salaries male vs female
employment_salary_test <- wilcox.test(starting_salaries_employment$Employment_Male, starting_salaries_employment$Employment_female)
employment_salary_test

#There is not a significant difference between starting female and male salaries

#running a mann-whittney u test for postdoc salaries male vs female
postdoc_salary_test <- wilcox.test(starting_salaries_postdoc$Postdoctoral_study_Male, starting_salaries_postdoc$Postoctoral_study_female)
postdoc_salary_test

#There is a significant difference between starting female and male salaries in post docs.

# using mann-whittney u because we are comparing medians

```

```{r, echo=FALSE}
#Exploring professors salaries in

#Creating summary of mean salary based on sex

salary_by_sex <- Faculty_Salary %>%
  group_by(Sex) %>%
  summarize(
    mean_salary = mean(Salary),
    sd_salary = sd(Salary),
    Max_salary = max(Salary),
    min_salary = min(Salary),
    sample_size = length(Salary)
  )

#creating a density graph to show the trend of how much male and female professors make
prof_salary_graph <- ggplot(Faculty_Salary, aes(x=Salary)) +
  geom_density(aes(color=Sex, fill=Sex), alpha=0.3) +
  theme_classic() +
  labs(x = "Salary (USD)", y = "Density")

prof_salary_graph

#Creating a scatterplot of the salary data
prof_salary_pointgraph_Sex <- ggplot(Faculty_Salary, aes(x=Years_Faculty_Service, y=Salary)) + 
  geom_point(aes(color=Sex, pch = Discipline)) +
  theme_classic() +
  facet_wrap(~Sex)

prof_salary_pointgraph_Sex

#graph does appear to have some linearity

#Create a graph to view linearity by discipline
prof_salary_pointgraph_Discipline <- ggplot(Faculty_Salary, aes(x=Years_Faculty_Service, y=Salary)) + 
  geom_point(aes(color=Sex, pch = Discipline)) +
  theme_classic() +
  facet_wrap(~Discipline)

prof_salary_pointgraph_Discipline

#Create a graph to view linearity by discipline
prof_salary_pointgraph_rank <- ggplot(Faculty_Salary, aes(x=Years_Faculty_Service, y=Salary)) + 
  geom_point(aes(color=Sex, pch = Discipline)) +
  theme_classic() +
  facet_wrap(~Faculty_Rank)

prof_salary_pointgraph_rank
```


```{r, echo=FALSE}
# Faculty salaries model 1

Faculty_salary_lm1 <- lm(Salary ~ Faculty_Rank + Discipline + Years_Since_PhD + Years_Faculty_Service + Sex, data = Faculty_Salary)

summary(Faculty_salary_lm1)

```

```{r, echo=FALSE}
# Faculty Salaries model 2

#adjusting the factor levels for Faculty Rank, Discipline and Sex
Faculty_Salary$Faculty_Rank <- factor(Faculty_Salary$Faculty_Rank)
Faculty_Salary$Discipline <- factor(Faculty_Salary$Discipline)
Faculty_Salary$Sex <- factor(Faculty_Salary$Sex)

Faculty_Salary$Faculty_Rank <- fct_relevel(Faculty_Salary$Faculty_Rank, "Prof")
Faculty_Salary$Sex <- fct_relevel(Faculty_Salary$Sex, "Male")

Faculty_salary_lm2 <- lm(Salary ~ Faculty_Rank + Discipline + Years_Since_PhD + Years_Faculty_Service + Sex, data = Faculty_Salary)

summary(Faculty_salary_lm2)

```
```{r, echo=FALSE}
# Checking assumptions for model 2
plot(Faculty_salary_lm2)
#residuals appear to have a pattern, homoscacity is false in this model

```
```{r, echo=FALSE}
#checking Faculty data for collinearity
pairs(Faculty_Salary)

# There appears to be some collinearity between Years since PhD and Years of Faculty Service and Faculty Rank
#will create models with only one of each

```

```{r, echo=FALSE}
#Model 3 without Years since PhD
Faculty_salary_lm3 <- lm(Salary ~ Faculty_Rank + Discipline +  Years_Faculty_Service + Sex, data = Faculty_Salary)

summary(Faculty_salary_lm3)

#not a great model because years of faculty service negatively influence salary
```

```{r, echo=FALSE}
#Checking assumuntion for model 3
plot(Faculty_salary_lm3)
```

```{r, echo=FALSE}
#Model 4 without Years of Service

Faculty_salary_lm4 <- lm(Salary ~ Faculty_Rank + Discipline + Years_Since_PhD +  Sex, data = Faculty_Salary)

summary(Faculty_salary_lm4)
#this model makes sense but there is there is no justification for removing Faculty years of service
```

```{r, echo=FALSE}
#checking assumptions on model 4
plot(Faculty_salary_lm4)

```

```{r, echo=FALSE}
#Model 5 without Faculty Rank
Faculty_salary_lm5 <- lm(Salary ~  Discipline + Years_Since_PhD + Years_Faculty_Service + Sex, data = Faculty_Salary)

summary(Faculty_salary_lm5)
#Bad model because as Years of Faculty Service increase salary goes down $770
```

```{r, echo=FALSE}
#Model 6 Model without discipline and Years since phd
Faculty_salary_lm6 <- lm(Salary ~ Faculty_Rank + Years_Faculty_Service + Sex, data = Faculty_Salary)

summary(Faculty_salary_lm6)
#Certain variable coeffiencts do not appear as I would expect them

```


```{r, echo=FALSE}
# Model 7 Model with an interaction term between years of faculty service and faculty rank
Faculty_salary_lm7 <- lm(Salary ~ Faculty_Rank + Discipline + Years_Since_PhD + Years_Faculty_Service + Sex + Faculty_Rank*Years_Faculty_Service, data = Faculty_Salary)

summary(Faculty_salary_lm7)
#not a great model certain coefficent don't make sense

```

```{r, echo=FALSE}
# Model 8; Model with interaction term and without Years since PhD
Faculty_salary_lm8 <- lm(Salary ~ Faculty_Rank + Discipline + Years_Faculty_Service + Sex + Faculty_Rank*Years_Faculty_Service, data = Faculty_Salary)

summary(Faculty_salary_lm8)

plot(Faculty_salary_lm8)
```

```{r, echo=FALSE}
# Model 9 Model with interaction and without discipline or Years since phd
Faculty_salary_lm9 <- lm(Salary ~ Faculty_Rank  + Years_Faculty_Service + Sex + Faculty_Rank*Years_Faculty_Service, data = Faculty_Salary)

summary(Faculty_salary_lm9)
#Variable coefficients for years of service and asstprof:years of service don't make logical sense
```

